spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${secrets.KAKAO_CLIENT_ID}
            client-name: Kakao
            client-secret: ${secrets.KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth/callback/{registrationId}"
            scope: account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

server:
  port: 80