spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.142.48.252:3306/health2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&sessionVariables=group_concat_max_len=8192&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: cos
    password: cos1234

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect

server:
  port: 80